/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 pomnik.gltf --output Pomnik.js 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pomnik.gltf')
  return (
    <group scale={0.3} {...props} dispose={null}>
      <mesh geometry={nodes.A.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2.geometry} material={materials['default']} />
      <mesh geometry={nodes._.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.D.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_2.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_2.geometry} material={materials['default']} />
      <mesh geometry={nodes['2'].geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_3.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_3.geometry} material={materials['default']} />
      <mesh geometry={nodes['0'].geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_4.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_4.geometry} material={materials['default']} />
      <mesh geometry={nodes['1'].geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_5.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_5.geometry} material={materials['default']} />
      <mesh geometry={nodes['5'].geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_6.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_6.geometry} material={materials['default']} />
      <mesh geometry={nodes.K.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_7.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_7.geometry} material={materials['default']} />
      <mesh geometry={nodes.O.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_8.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_8.geometry} material={materials['default']} />
      <mesh geometry={nodes.R.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_9.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_9.geometry} material={materials['default']} />
      <mesh geometry={nodes.Y.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_10.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_10.geometry} material={materials['default']} />
      <mesh geometry={nodes.T.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_11.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_11.geometry} material={materials['default']} />
      <mesh geometry={nodes.O_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_12.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_12.geometry} material={materials['default']} />
      <mesh geometry={nodes.W.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_13.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_13.geometry} material={materials['default']} />
      <mesh geometry={nodes.S.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_14.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_14.geometry} material={materials['default']} />
      <mesh geometry={nodes.K_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_15.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_15.geometry} material={materials['default']} />
      <mesh geometry={nodes.A_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_16.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_16.geometry} material={materials['default']} />
      <mesh geometry={nodes.K_2.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_17.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_17.geometry} material={materials['default']} />
      <mesh geometry={nodes.R_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_18.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_18.geometry} material={materials['default']} />
      <mesh geometry={nodes.Y_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_19.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_19.geometry} material={materials['default']} />
      <mesh geometry={nodes.S_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_20.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_20.geometry} material={materials['default']} />
      <mesh geometry={nodes.T_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_21.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_21.geometry} material={materials['default']} />
      <mesh geometry={nodes.Y_2.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_22.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_22.geometry} material={materials['default']} />
      <mesh geometry={nodes.N.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_23.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_23.geometry} material={materials['default']} />
      <mesh geometry={nodes.A_2.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_24.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_24.geometry} material={materials['default']} />
      <mesh geometry={nodes.F.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_25.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_25.geometry} material={materials['default']} />
      <mesh geometry={nodes.U.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_26.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_26.geometry} material={materials['default']} />
      <mesh geometry={nodes.N_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_27.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_27.geometry} material={materials['default']} />
      <mesh geometry={nodes.D_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_28.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_28.geometry} material={materials['default']} />
      <mesh geometry={nodes.A_3.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_29.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_29.geometry} material={materials['default']} />
      <mesh geometry={nodes.T_2.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_30.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_30.geometry} material={materials['default']} />
      <mesh geometry={nodes.O_2.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_31.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_31.geometry} material={materials['default']} />
      <mesh geometry={nodes.R_2.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zaokrąglenie_32.geometry} material={materials['default']} />
      <mesh geometry={nodes.Zakończenie_2_32.geometry} material={materials['default']} />
      <mesh geometry={nodes.Sześcian.geometry} material={materials['default']} />
      <mesh geometry={nodes.Połącz_obiekty.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.K_3.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_1.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_33.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.s.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_2.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_34.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.__1.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_3.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_35.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.B.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_4.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_36.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.I.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_5.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_37.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.S_2.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_6.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_38.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.K_4.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_7.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_39.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.U_1.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_8.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_40.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.P.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_9.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_41.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.A_4.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_10.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_42.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.L.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_11.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_43.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.B_1.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_12.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_44.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.I_1.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_13.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_45.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.N_2.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_14.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_46.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.M.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_15.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_47.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.A_5.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_16.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_48.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Ł.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_17.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_49.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Y_3.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_18.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_50.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.S_3.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_19.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_51.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.I_2.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_20.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_52.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.A_6.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_21.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_53.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.K_5.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_22.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_54.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['1_1'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_23.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_55.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['9'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_24.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_56.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['1_2'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_25.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_57.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['7'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_26.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_58.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.__2.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_27.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_59.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['2_1'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_28.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_60.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['0_1'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_29.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_61.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['1_3'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_30.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_62.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes['1_4'].geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zaokrąglenie_2_31.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.Zakończenie_2_63.geometry} material={materials['Marble - White & Grey Veins - Shader']} />
      <mesh geometry={nodes.GenericHead_1.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/pomnik.gltf')
